### ISSUE TITLE
Can you please explain your video memory code?

### ISSUE THREAD

**Issue by omerjerk** [Sid-2D/Intel-8080-Emulator#2]
I am writing an Intel 8080 emulator in C. I am mostly stuck with understanding the format of the video memory. As far as I read, it's 7k in size but I am not getting how it is to be displayed on a 256 * 224 size canvas.

Any tip would be greatly appreciated. :)

**Comment by Sid-2D** [comment]
The space invaders designers used a clever way to store these many pixels in just 7K. Each byte can light up to 8 pixels as each bit refers to ON/OFF state for 1 pixel. So basically, 256*224/8 = 7168 (7K) bytes.

**Comment by omerjerk** [comment]
Ah. Thank you so much. No I get it. I have got a primitive version running. :)

https://github.com/omerjerk/hello-8080
